# configs.yaml - UTF-8 인코딩
seed: 42

# GPU 및 성능 최적화 설정
params:
  cuda: False  # GPU 사용 활성화
  device: "cuda"  # 명시적 디바이스 지정
  mixed_precision: True  # Mixed precision 사용
  gradient_accumulation_steps: 1  # 그래디언트 누적 스텝
  max_grad_norm: 1.0  # 그래디언트 클리핑
  pin_memory: True  # 메모리 핀닝
  prefetch_factor: 2  # 프리페치 팩터

# 로깅 설정
logger:
  logger: tensorboard 
  logdir: logs
  log_interval: 10  # 로깅 간격
  save_interval: 100  # 모델 저장 간격

# 모델 하이퍼파라미터 - VRNN-GAT 모델 (models.py)
model_vrnn:
  use_rnn: True
  use_gat: True
  hidden_dim: 64  # hidden_dim 증가
  z_dim: 32
  gat_dim: 32  # gat_dim 증가
  num_heads: 4
  dropout: 0.1
  act_dim: 3
  
# 모델 하이퍼파라미터 - SCM 모델 (models_scm.py)
model_scm:
  gat_type: "causal_enhanced"  # "none", "basic", "causal", "causal_structure", "causal_enhanced"
  hidden_dim: 64
  gat_dim: 32
  num_heads: 4
  dropout: 0.1
  act_dim: 3
  use_gat: True
  use_causal_prior: True
  use_causal_weighting: True
  use_causal_gating: True
  use_causal_mask: True
  scm_hidden_dim: 64
  causal_consistency_weight: 0.1
  causal_regularization_weight: 0.01

model_scm2:
  n_agents: 2           # 환경에 맞게 동기화 필요
  num_atoms: 2          # n_agents와 동일하게
  obs_dim: 16           # 환경에 맞게
  edge_types: 2         # ACDrepo 기본값
  var: 5e-5             # recon loss 분산
  scm_hidden_dim: 64
  rnn_hidden_dim: 64
  num_heads: 4
  act_dim: 3

# 학습 하이퍼파라미터
training:
  lr: 5e-4  # 학습률 증가
  lr_vae: 1e-4  # VAE 학습률
  gamma: 0.99  # 할인 팩터
  gae_lambda: 0.95  # GAE 람다
  ent_coef: 0.05  # 엔트로피 계수 증가 (탐험 촉진)
  value_coef: 1.0  # 가치 함수 계수
  nll_coef: 1.0  # NLL 계수
  kl_coef: 1.0  # KL 계수
  coop_coef: 0.5  # 협력 계수
  ema_alpha: 0.99  # EMA 알파
  total_steps: 3000  # 총 학습 스텝 대폭 증가
  ep_num: 5 # 에피소드 수 증가
  vae_loss_type: "standard" # "standard", "beta_vae"
  use_kl_annealing: True

  if vae_loss_type == "beta_vae":
    beta: 1.0
    capacity: 0.0
    target_capacity: 0.0

dectiger:
  task: dectiger
  maxstep: 2
  obs_dim: 16
  nagents: 2

rware:
  task: rware
  nagents: 2
  maxstep: 100
  layout: |
    .x..x.
    .x..x.
    ......
    ..gg..

mpe:
  task: mpe_simple_spread
  maxstep: 25
  nagents: 3

smax:
  task: smax # 2s3z
  nagents: 5
  maxstep: 100

switch:
  task: switch
  nagents: 2
  maxstep: 50

pp:
  task: pp
  nagents: 2
  maxstep: 100

foraging:
  task: foraging
  nagents: 2
  maxstep: 100